// Travel interests categories and options
export const travelInterests: Record<string, string[]> = {
  "Culture & History": [
    "Historical Sites & Landmarks",
    "Museums",
    "UNESCO World Heritage Sites",
    "Ancient Ruins",
    "Castles & Palaces",
    "Religious Sites",
    "Local Traditions & Festivals",
    "Indigenous Cultures",
    "Architectural Styles",
    "Specific Historical Periods",
  ],
  "Nature & Outdoors": [
    "Beaches & Coastlines",
    "Mountains & Hiking",
    "Forests & National Parks",
    "Lakes & Rivers",
    "Deserts & Canyons",
    "Gardens & Botanical Gardens",
    "Waterfalls",
    "Volcanoes & Geothermal Areas",
    "Specific types of flora & fauna",
  ],
  "Food & Drink": [
    "Local Cuisine & Regional Specialties",
    "Fine Dining & Michelin Star Restaurants",
    "Street Food & Food Markets",
    "Cooking Classes & Culinary Tours",
    "Wineries & Vineyards",
    "Breweries & Craft Beer",
    "Coffee Culture & Cafes",
    "Specific Cuisines",
    "Dietary Preferences",
    "Food Festivals & Events",
  ],
  "Art & Entertainment": [
    "Art Museums & Galleries",
    "Live Music Venues",
    "Theaters & Performing Arts",
    "Cinemas & Film Festivals",
    "Street Art & Graffiti",
    "Local Craft Markets & Artisan Workshops",
    "Design & Fashion",
    "Nightlife & Entertainment",
  ],
  "Adventure & Activities": [
    "Hiking & Trekking",
    "Water Sports",
    "Winter Sports",
    "Cycling & Mountain Biking",
    "Rock Climbing & Bouldering",
    "Wildlife Safaris & Animal Encounters",
    "Extreme Sports",
    "Spas & Wellness Retreats",
    "Yoga & Meditation Retreats",
  ],
  "Shopping & Urban Exploration": [
    "Shopping Districts & Malls",
    "Local Markets & Bazaars",
    "Unique Souvenir Shopping",
    "Urban Parks & Green Spaces",
    "City Walking Tours & Bike Tours",
    "Specific types of shops",
    "Architecture & Urban Design Appreciation",
  ],
  "Specific Hobbies & Interests": [
    "Photography",
    "Birdwatching",
    "Astronomy & Stargazing",
    "Gardening & Horticulture",
    "Genealogy & Ancestry Research",
    "Learning a new language",
    "Volunteering & Responsible Tourism",
    "Specific sports",
    "Crafting & DIY",
  ],
};

// Travel styles categories and options
export const travelStyles: Record<string, string[]> = {
  Budget: [
    "Budget-Friendly/Backpacking",
    "Mid-Range",
    "Luxury",
    "Flashpacking (Budget with some splurges)",
  ],
  "Pace & Detail Level": [
    "Relaxed Pace",
    "Moderate Pace",
    "Fast-Paced/Packed",
    "Highly Detailed Itinerary",
    "Flexible Itinerary",
  ],
  "Travel Type & Group": [
    "Solo Travel",
    "Couples/Romantic Getaway",
    "Family Travel",
    "Group Travel",
    "Business Travel",
    "Honeymoon",
    "Pet-Friendly Travel",
    "Accessible Travel",
  ],
  "Transportation Preference": [
    "Flights Preferred",
    "Train Travel Preferred",
    "Road Trips/Driving Preferred",
    "Sustainable/Eco-Friendly Transportation",
    "Cruises/Boat Travel",
  ],
  "Accommodation Style": [
    "Luxury Hotels",
    "Boutique Hotels",
    "Budget Hotels/Hostels",
    "Bed & Breakfasts (B&Bs)",
    "Vacation Rentals",
    "Camping/Glamping",
    "Eco-Lodges/Sustainable Accommodation",
  ],
  "Social Interaction Level": [
    "Social Travel",
    "Independent Travel",
    "Local Immersion",
  ],
  "Travel Season Preference": [
    "Warm Weather Destinations",
    "Cold Weather/Winter Destinations",
    "Shoulder Season Travel",
    "Specific Season/Months Preferred",
  ],
};
